version: "3.8"
services:
  etcd:
    image: bitnami/etcd
    restart: always
    ports:
      - "2379:2379"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
  scylla:
    image: scylladb/scylla
    ports:
      - "9042:9042"
  broker:
    image: broker
    restart: always
    ports:
      - "5000:80"
    links:
      - etcd
    environment:
      - ETCD_HOST=http://etcd:2379
    depends_on:
      - "etcd"
  modelapi:
    image: model_api
    depends_on:
      - "etcd"
      - "scylla"
    restart: always
    links:
      - scylla
      - etcd
    environment:
      - MODEL_ETCD_HOST=etcd
      - MODEL_SCYLLA=scylla


